### PR TITLE
Implemented method for saving Json

### PR DESCRIPTION
**Pull request by abdulmannans**
Implement method for saving Json #19

### CODE REVIEW

**Comment by roberto-butti** [comment]
Thank you @abdulmannans  for the PR!

Becuase I would like to introduce also this implementation i already wrote in the initial issue:

> If the file already exists, it returns false (and the file is not saved) unless the second parameter is specified. The second parameter is overwrite (false as default). IF the file exists and overwrite is true, then the content of the file is replaced.

Let me know if you want to add this logic in this PR, or if you don't want, let me know, i can merge the PR and eventually implement it in another new one.

Thank you

**Comment by abdulmannans** [comment]
@roberto-butti I would love to implement the logic.

**Comment by abdulmannans** [comment]
@roberto-butti I have done the requested changes.

**Comment by roberto-butti** [comment]
it looks great!
And i like also the multiple tests cases! Great Job @abdulmannans

**Comment by roberto-butti** [comment]
it closes #19 , thank you @abdulmannans

**Comment by abdulmannans** [comment]
@roberto-butti Thank you for merging .

**Pull request merged**
