### PR TITLE
Add getFormattedByte

### PR DESCRIPTION
**Pull request by MatteoGheza**
This PR addresses issue #25 by implementing the requested functionality. I am new to this codebase, so there may be some errors

### CODE REVIEW

**Comment by roberto-butti** [comment]
Hi @MatteoGheza thank you for your effort on this PR.
I see the WIP label in the title, so let me know when you completed it , and i can review it.
One suggestion: I wrote a snippet with a static function in the feature request. Reading your implementation, I think you can pick the code of the static function and put it directly in the `getFormattedByte` function.
So the getFormattedByte doesn't need to call a static function.

If you don'r have time to do it, no worries, eventually i can merge it, and i can fix a bit.
Let me know your thoughts.

Thank you

**Comment by MatteoGheza** [comment]
Done, thanks for the feedback

**Comment by MatteoGheza** [comment]
Thanks for catching that, @roberto-butti! I've updated the getFormattedByte method.
Let me know if there’s anything else to adjust!

**Comment by roberto-butti** [comment]
Amazing job @MatteoGheza , I'm going to merge it

**Pull request merged**
